name: Install artplayer-tool-chromecast and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your project's Node.js version (20.19.4 from error)
          cache: 'pnpm' # Cache pnpm dependencies for faster builds

      # Install pnpm using pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify pnpm version (adjust if needed, e.g., latest or specific version)
          run_install: false # We'll run pnpm install in a separate step

      # Verify pnpm installation
      - name: Verify pnpm installation
        run: pnpm --version

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # Explicitly install artplayer-tool-chromecast
      - name: Install artplayer-tool-chromecast
        run: pnpm add artplayer-tool-chromecast

      # Build the Next.js project
      - name: Build project
        run: pnpm run build

      # Optional: Run tests if they exist
      # Uncomment the following step if your project has a test script
      # - name: Run tests
      #   run: pnpm run test
      #   continue-on-error: true # Allow workflow to continue if tests fail
