name: Add Chromecast Plugin and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  add-dependency-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensure checkout can push changes

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0 # Match package.json packageManager version
          run_install: false # We'll handle installation manually

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4' # Matches your Docker setup (node:20.19.4)
          cache: 'pnpm' # Cache pnpm dependencies
          cache-dependency-path: '**/pnpm-lock.yaml'

      # Verify pnpm installation and registry
      - name: Verify pnpm installation and registry
        run: |
          echo "PATH: $PATH"
          which pnpm || echo "pnpm not found"
          pnpm --version || echo "pnpm version command failed"
          pnpm config set registry https://registry.npmjs.org/
          pnpm config get registry
          pnpm view artplayer-tool-chromecast || echo "artplayer-tool-chromecast not found in npm registry"
        shell: bash

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install
        shell: bash

      # Install artplayer-tool-chromecast
      - name: Install artplayer-tool-chromecast
        run: pnpm add artplayer-tool-chromecast || echo "Failed to install artplayer-tool-chromecast; check package name or registry"
        shell: bash
        continue-on-error: true # Allow workflow to continue if package is not found

      # Build the Next.js project
      - name: Build project
        run: pnpm run build
        shell: bash

      # Commit changes to package.json and pnpm-lock.yaml
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "Add artplayer-tool-chromecast dependency" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        continue-on-error: true # Allow workflow to continue if no changes to commit
