name: Install artplayer-tool-chromecast and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment with pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust to match your project's Node.js version
          cache: 'pnpm' # Cache pnpm dependencies for faster builds

      # Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version # Verify pnpm installation

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # Explicitly install artplayer-tool-chromecast
      - name: Install artplayer-tool-chromecast
        run: pnpm add artplayer-tool-chromecast

      # Build the Next.js project
      - name: Build project
        run: pnpm run build

      # Optional: Run tests if they exist
      # Uncomment the following step if your project has a test script
      # - name: Run tests
      #   run: pnpm run test
      #   continue-on-error: true # Allow workflow to continue if tests fail
